### ISSUE TITLE
leaflet map fixed!

### ISSUE THREAD

**Issue by katcorr** [stat231-f20/Blog-HealthAndJusticeLeague#3]
@goni99 

Bella, oh my gosh, I just figured out the leaflet issue, and it's such a silly thing, I'm sorry I missed seeing this before!  Although `palchange3` is defined above, in the DALY leaflet plot, it had been referring to the wrong palette function (`pal2017_3 `, not `palchange3`).  Once I updated it to `palchange3`, it colors everything correctly!

I pushed the change to the repo, and you can see the exact changes I made [here](https://github.com/stat231-f20/Blog-HealthAndJusticeLeague/commit/d41e225b380fc4065e68b4421f49b82ab1294656#diff-444e15472c664d1f66b5bca0ab49cba5cbb2693f5aeb00b32377137910b89966) and [here](https://github.com/stat231-f20/Blog-HealthAndJusticeLeague/commit/5cadac8f4801a4eef8008e5a273b8cf601a37a6f#diff-444e15472c664d1f66b5bca0ab49cba5cbb2693f5aeb00b32377137910b89966).

**Comment by goni99** [comment]
I realized it too! It was actually such a silly mistake on my part hahahahaha😯 
Thank you for your help!
